import Chat from "@/components/chat";
import MessageInput from "@/components/inputs/MessageInput";
import { toRoomName } from "@/utils/room-param-mask";
import { GetServerSideProps, InferGetServerSidePropsType } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import io from "socket.io-client";

const socket = io("http://localhost:8080");

export default function Room({
  roomName,
  username,
}: InferGetServerSidePropsType<typeof getServerSideProps>) {

  return (
    <>
      <Head>
        <title>Chat App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col min-h-screen justify-center items-center">
        {toRoomName(roomName)}

        <Chat socket={socket} localUser={username} roomName={roomName} />
      </main>
    </>
  );
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const roomName = context.params?.name;
  const username = context.query?.user;
  return {
    props: {
      roomName: roomName,
      username: username,
    },
  };
};
