import JoinRoomForm from "@/components/forms/JoinRoom";
import ChatLogo from "@/components/misc/chat-logo";
import DotPattern from "@/components/misc/dot-pattern";
import Head from "next/head";
import io from "socket.io-client";

export default function Home() {
  return (
    <>
      <Head>
        <title>Chat App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col min-h-screen justify-center items-center">
        <div className="flex flex-col items-center gap-10">
          <ChatLogo />
          <JoinRoomForm />
        </div>

        <DotPattern className="-z-10 absolute top-16 right-6 w-48 h-80" />
        <DotPattern
          fill
          className="-z-10 absolute bottom-16 left-6 w-48 h-80"
        />
      </main>
    </>
  );
}
